name: Generate Match Logs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-logs:
    environment: workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate logs
        env:
          PUBG_API_KEY: ${{ secrets.PUBG_API_KEY }}
        run: bun run generate-match-logs

      - name: Commit and push if changed
        env:
          TZ: Asia/Seoul
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          TODAY="$(date +'%F %H시%M분%S초')"
          git add .
          git commit -m "generate-match-logs:${TODAY}"
          git push
